### ISSUE TITLE
Two items are pointing to the same link in "Page 2"

### ISSUE THREAD

**Issue by yilverdeja** [dim-pan/Entrepreneuership-Pretotype#1]
For `Page 2`, the following items in the image below are pointing to the same [link](https://communityclothing.co.uk/products/mensslimchino-navy?variant=31570051039286)

![image](https://user-images.githubusercontent.com/29952939/148650660-8a65ea23-0f1a-4c37-97a1-907487051966.png)

**Comment by dim-pan** [comment]
Fixed now, thank you for pointing that out! :)
